call plug#begin()
	Plug 'sainnhe/gruvbox-material'	
	Plug 'Fymyte/rasi.vim'
	Plug 'tmsvg/pear-tree'
call plug#end()

if has ('termguicolors')
	set termguicolors
endif

set ts=4
set sw=4
set bg=dark
set number
set linebreak

let g:gruvbox_material_enable_bold = 1
colorscheme gruvbox-material
